api_version = "2025-01"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "discount-logic"
type = "ui_extension"
uid = "3add9654-2d84-074a-059a-79f9df52579b5477f687"

# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.tsx"
# The target used here must match the target used in the module file (./src/DiscountFunctionSettings.tsx)
target = "admin.discount-details.function-settings.render"
